drm_hwcomposer: hwcutils: use <ui/Gralloc.h> with Android Q and later
Fixes the following building error with Android P:

external/drm_hwcomposer/utils/hwcutils.cpp:21:10: fatal error: 'ui/Gralloc.h' file not found
         ^~~~~~~~~~~~~~
1 error generated.

Fixes: add24cb7 ("drm_hwcomposer: stop using pixel_stride")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>