drm_hwcomposer: add allocator@2.0 and mapper@2.1 shared dependencies (Android P)
Fixes the following building errors after commit
add24cb7 "drm_hwcomposer: stop using pixel_stride"

In file included from external/drm_hwcomposer/utils/hwcutils.cpp:24:
frameworks/native/libs/ui/include/ui/Gralloc2.h:22:10: fatal error: 'android/hardware/graphics/allocator/2.0/IAllocator.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

frameworks/native/libs/ui/include/ui/Gralloc2.h:25:10: fatal error: 'android/hardware/graphics/mapper/2.1/IMapper.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Fixes: add24cb7 ("drm_hwcomposer: stop using pixel_stride")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>