drm_hwcomposer: bufferinfo/legacy: use DRM_FORMAT_XYUV8888 for Android Q and later (v2)
To avoid following building errors with Android P:

external/drm_hwcomposer/bufferinfo/legacy/BufferInfoLibdrm.cpp:61:57: error: use of undeclared identifier 'DRM_FORMAT_XYUV8888'
    {HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED, YCrCb, 1, DRM_FORMAT_XYUV8888},
                                                        ^
external/drm_hwcomposer/bufferinfo/legacy/BufferInfoLibdrm.cpp:68:23: error: invalid application of 'sizeof' to an incomplete type 'const struct droid_yuv_format []'
  for (int i = 0; i < ARRAY_SIZE(droid_yuv_formats); ++i)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/drm_hwcomposer/bufferinfo/legacy/BufferInfoLibdrm.cpp:64:30: note: expanded from macro 'ARRAY_SIZE'
                             ^~~
external/drm_hwcomposer/bufferinfo/legacy/BufferInfoLibdrm.cpp:78:23: error: invalid application of 'sizeof' to an incomplete type 'const struct droid_yuv_format []'
  for (int i = 0; i < ARRAY_SIZE(droid_yuv_formats); ++i)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/drm_hwcomposer/bufferinfo/legacy/BufferInfoLibdrm.cpp:64:30: note: expanded from macro 'ARRAY_SIZE'
                             ^~~
3 errors generated.

(v2) Resolve conflics after commit e2f2c929
     "drm_hwcomposer: enable code analysis using clang-tidy"

Fixes: add24cb7 ("drm_hwcomposer: stop using pixel_stride")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>