drm_hwcomposer: Backend: build with -Wno-c++17-extensions cppflag (Android P)
To avoid the following building error with Android P:

external/drm_hwcomposer/backend/Backend.cpp:115:15:
error: decomposition declarations are a C++17 extension [-Werror,-Wc++17-extensions]
  for (auto & [ z_order, layer ] : z_map) {
              ^~~~~~~~~~~~~~~~~~
1 error generated.

Fixes: ef3c797d ("drm_hwcomposer: Add backend-dependent validation for HwcDisplay class")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>