drm_hwcomposer: Backend: build with -Wno-sign-compare cppflag (Android P)
To avoid the following building error with Android P:

external/drm_hwcomposer/backend/Backend.cpp:89:62: error: comparison of integers of different signs: 'int' and 'std::__1::map<unsigned int, android::DrmHwcTwo::HwcLayer *, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, android::DrmHwcTwo::HwcLayer *> > >::size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
    bool testing_needed = !(client_start == 0 && client_size == z_map.size());
                                                 ~~~~~~~~~~~ ^  ~~~~~~~~~~~~
1 error generated.

Fixes: ef3c797d ("drm_hwcomposer: Add backend-dependent validation for HwcDisplay class")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>